version: "3.1"
services:

  backend:
    build:
      context: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    depends_on:
      - mongo
    networks:
      - mynetwork
    ports:
      - "5000:5000"

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - mynetwork
    ports:
      - "8000:27017"
  
  client:
    stdin_open: true
    build:
      context: ./client
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  mynetwork:
    driver: bridge
