version: "3.1"
services:
 client:
  context:
   command: cd client
  dependencis:
   command: npm install
  build:
   command: npm start
  ports:
  -3000:3000
  
 server:
  context:
   command: cd backend
  dependencies:
   command: npm install
  build:
   command: npm start
  depends_on:
  - mongo
  ports:
  - 5000:5000
 mongo:
  image: mongo
