version: "3.1"
services:

  client:
    image: ip2_client:1.0.0    
    stdin_open: true
    build:
      context: ./client
    depends_on:
      - backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    networks:
      - mynetwork
    ports:
      - "3000:3000"

  backend:
    image: ip2_backend:1.0.0
    build:
      context: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    depends_on:
      - mongo
    networks:
      - mynetwork
    ports:
      - "5000:5000"

  mongo:
    container_name: mongo
    image: mongo:6.0-jammy
    restart: always
    networks:
      - mynetwork
    ports:
      - "8000:27017"
    volumes:
      - mongo-persistent-storage:/data/db

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo-persistent-storage:
    # driver: local
    # driver_opts:
    #   size: 50m
