apiVersion: v1
kind: Pod
metadata:
 name: ecommerce-app
spec:
 containers:
 - image: ckodalo/ip2_backend:1.0.0
   name: backend
   ports:
   - containerPort: 5000
     protocol: TCP
   imagePullPolicy: IfNotPresent
 - image: ckodalo/ip2_client:1.0.0
   name: client
   ports:
   - containerPort: 3000
     protocol: TCP
   imagePullPolicy: IfNotPresent
